/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cloud.bangover.saga.orchestrator

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
